FROM python:3.11-slim
WORKDIR /app
COPY . .
RUN pip install --no-cache-dir -r requirements.txt

# по умолчанию запуск coverage + pytest
CMD ["sh", "-c", "coverage run -m pytest && coverage report -m"]

